### ISSUE TITLE
use constants 

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#3]
define constants for your configuration values
https://github.com/asharif123/slot_machine/blob/14315b7a80e1f630ce23fd669a679d1b5e753fd2/Program.cs#L15

and use them within outputs etc
https://github.com/asharif123/slot_machine/blob/14315b7a80e1f630ce23fd669a679d1b5e753fd2/Program.cs#L20

**Comment by mayisa87** [comment]
You can define your starting value 50 as a constant like Michael proposed, and then have a variable that is initialized with this constant.

So you could have a const int STARTING_BANK_AMOUNT = 50;
and instead of assigning hardcoded 50 to your winnings, you can use the constant. And you can use the constant in your output then too

**Comment by asharif123** [comment]
fixed issue #3 using constants
